import type { TestListItem } from "~/types/test";

export default defineEventHandler(() => {
  const testList: TestListItem[] = [
    {
      id: "phq9",
      title: "PHQ-9 抑郁筛查量表",
      englishName: "Patient Health Questionnaire-9",
      description: "用于评估过去两周内的抑郁症状严重程度，包含9个核心问题",
      duration: "约3-5分钟",
      questionsCount: 9,
      tags: ["抑郁", "快速"],
      category: "symptom",
    },
    {
      id: "gad7",
      title: "GAD-7 焦虑筛查量表",
      englishName: "Generalized Anxiety Disorder-7",
      description: "用于评估广泛性焦虑症状的严重程度，快速识别焦虑倾向",
      duration: "约2-3分钟",
      questionsCount: 7,
      tags: ["焦虑", "快速"],
      category: "symptom",
    },
    {
      id: "pss",
      title: "压力感知量表",
      englishName: "Perceived Stress Scale (PSS-10)",
      description: "用于评估您在过去一个月中的压力感知水平，了解压力管理需求",
      duration: "约4-6分钟",
      questionsCount: 10,
      tags: ["压力", "自我感知"],
      category: "special",
    },
    {
      id: "scl90",
      title: "SCL-90 症状自评量表",
      englishName: "Symptom Checklist-90",
      description: "全面的心理健康评估工具，评估9个维度的心理症状，专业详尽",
      duration: "约15-20分钟",
      questionsCount: 90,
      tags: ["综合评估", "心理健康"],
      category: "symptom",
    },
    {
      id: "sds",
      title: "抑郁自评量表",
      englishName: "Self-Rating Depression Scale (SDS)",
      description: "标准化的抑郁症状自评工具，帮助了解抑郁倾向程度",
      duration: "约5-8分钟",
      questionsCount: 20,
      tags: ["抑郁", "标准量表"],
      category: "symptom",
    },
    {
      id: "sas",
      title: "焦虑自评量表",
      englishName: "Self-Rating Anxiety Scale (SAS)",
      description: "标准化的焦虑症状自评工具，快速评估焦虑水平",
      duration: "约5-8分钟",
      questionsCount: 20,
      tags: ["焦虑", "标准量表"],
      category: "symptom",
    },
    {
      id: "mbti",
      title: "MBTI 人格测试",
      englishName: "Myers-Briggs Type Indicator",
      description:
        "基于荣格心理学理论，结合情境假设与日常问题，评估16种人格类型以及内在/外在性格差异",
      duration: "约15-18分钟",
      questionsCount: 109,
      tags: ["人格", "性格分析"],
      category: "personality",
    },
    {
      id: "sccs",
      title: "自我和谐量表",
      englishName: "Self-Consistency and Congruence Scale (SCCS)",
      description: "评估自我与经验的关系，了解内心和谐程度，包含35个问题",
      duration: "约8-10分钟",
      questionsCount: 35,
      tags: ["自我认知", "心理和谐"],
      category: "special",
    },
    {
      id: "temperament",
      title: "气质类型测试",
      englishName: "Temperament Type Test",
      description:
        "基于希波克拉底的四液说，评估胆汁质、多血质、粘液质、抑郁质四种气质类型",
      duration: "约10-15分钟",
      questionsCount: 60,
      tags: ["气质", "行为风格"],
      category: "personality",
    },
    {
      id: "bdc",
      title: "伯恩斯抑郁症清单",
      englishName: "Burns Depression Checklist (BDC)",
      description:
        "美国心理治疗专家David D. Burns博士设计的抑郁症自我诊断表，帮助快速评估抑郁情绪程度",
      duration: "约3-5分钟",
      questionsCount: 15,
      tags: ["抑郁", "快速"],
      category: "symptom",
    },
    {
      id: "epq",
      title: "艾森克人格问卷",
      englishName: "Eysenck Personality Questionnaire (EPQ)",
      description:
        "英国心理学家艾森克编制的人格测量工具，测评内外向、情绪稳定性、精神质三个维度",
      duration: "约15-20分钟",
      questionsCount: 88,
      tags: ["人格", "气质"],
      category: "personality",
    },
    {
      id: "epq-rsc",
      title: "艾森克人格问卷简式量表",
      englishName:
        "Eysenck Personality Questionnaire Revised Short Scale (EPQ-RSC)",
      description:
        "北京大学钱铭怡教授等修订的中国版艾森克人格问卷简式版，评估内外向(E)、神经质(N)、精神质(P)、掩饰性(L)四个维度",
      duration: "约10-15分钟",
      questionsCount: 48,
      tags: ["人格", "快速", "中国常模"],
      category: "personality",
    },
    {
      id: "emotional-stability",
      title: "情绪稳定性测试",
      englishName: "Emotional Stability Test",
      description: "评估您的情绪稳定程度，了解情绪波动情况和心理抗压能力",
      duration: "约5-10分钟",
      questionsCount: 30,
      tags: ["情绪", "心理韧性"],
      category: "special",
    },
    {
      id: "sixteenPF",
      title: "卡特尔16种人格因素问卷",
      englishName: "Sixteen Personality Factor Questionnaire (16PF)",
      description:
        "美国卡特尔教授编制，评估16种根源人格特质，广泛应用于心理咨询、职业指导等领域",
      duration: "约30-45分钟",
      questionsCount: 187,
      tags: ["人格", "职业发展", "专业测评"],
      category: "personality",
    },
    {
      id: "bpns",
      title: "基本心理需求满足量表",
      englishName: "Basic Psychological Need Satisfaction Scale (BPNS)",
      description:
        "基于自我决定理论，评估自主需求、胜任需求和归属需求的满足程度",
      duration: "约3-5分钟",
      questionsCount: 21,
      tags: ["心理需求", "幸福感"],
      category: "special",
    },
    {
      id: "ipip-eis",
      title: "情绪智力量表",
      englishName: "Emotional Intelligence Scale (IPIP-EIS)",
      description:
        "基于国际人格项目库开发的情绪智力测量工具，评估情绪知觉、表达、管理和共情等能力",
      duration: "约8-12分钟",
      questionsCount: 64,
      category: "special",
      tags: ["情绪智力", "共情能力"],
    },
    {
      id: "mdq",
      title: "心境障碍问卷",
      englishName: "Mood Disorder Questionnaire (MDQ)",
      description: "双相谱系障碍的标准化筛查工具，评估躁狂/轻躁狂症状，包含15个问题",
      duration: "约3-5分钟",
      questionsCount: 15,
      tags: ["躁狂", "双相", "快速"],
      category: "symptom",
    },
    {
      id: "asrm",
      title: "Altman躁狂自评量表",
      englishName: "Altman Self-Rating Mania Scale (ASRM)",
      description: "快速评估过去一周的躁狂症状严重程度，包含5个核心问题",
      duration: "约1-2分钟",
      questionsCount: 5,
      tags: ["躁狂", "快速"],
      category: "symptom",
    },
    {
      id: "rses",
      title: "Rosenberg 自尊量表",
      englishName: "Rosenberg Self-Esteem Scale (RSES)",
      description: "评估个体的整体自我价值感与自尊水平，包含10个问题",
      duration: "约2-3分钟",
      questionsCount: 10,
      tags: ["自尊", "自我认知"],
      category: "special",
    },
    {
      id: "seven",
      title: "七美德与七宗罪",
      englishName: "Seven Deadly Sins & Seven Virtues Test",
      description: "分别测量 7 宗罪与 7 美德两条独立指数，罪与德互不抵消",
      duration: "约8-12分钟",
      questionsCount: 60,
      tags: ["人格", "自我认知", "趣味自评"],
      category: "personality",
    },
    {
      id: "psy-age",
      title: "心理年龄测验",
      englishName: "Psychological Age Test",
      description: "基于发展心理学的多维年龄模型，探究你的心理年龄。42 道题勾勒认知、情绪、时间观等七维画像，用「成熟度 × 少年感」双轴解读你的心理年龄",
      duration: "约5-8分钟",
      questionsCount: 43,
      tags: ["人格", "自我认知", "趣味自评"],
      category: "personality",
    },
    {
      id: "sioss",
      title: "自杀意念自评量表",
      englishName: "Self-rating Idea of Suicide Scale (SIOSS)",
      description:
        "夏朝云等（2002）编制，从绝望感、乐观感缺失与睡眠困扰等维度评估自杀意念，用于自杀风险的早期识别与筛查，含测谎条目校验作答效度",
      duration: "约3-5分钟",
      questionsCount: 26,
      tags: ["自杀意念", "危机筛查", "本土量表"],
      category: "symptom",
    },
    {
      id: "bis",
      title: "Barratt 冲动性量表",
      englishName: "Barratt Impulsiveness Scale (BIS-11)",
      description:
        "Patton等编制，评估注意力、运动和无计划三个维度的冲动性人格特质",
      duration: "约8-12分钟",
      questionsCount: 30,
      tags: ["冲动性", "人格特质"],
      category: "personality",
    },
    {
      id: "bpaq",
      title: "Buss-Perry 攻击性问卷",
      englishName: "Buss-Perry Aggression Questionnaire (BPAQ)",
      description:
        "Buss与Perry编制，从身体攻击、言语攻击、愤怒和敌意四个维度评估攻击性倾向",
      duration: "约6-10分钟",
      questionsCount: 29,
      tags: ["攻击性", "敌意"],
      category: "personality",
    },
    {
      id: "ymrs",
      title: "杨氏躁狂评定量表",
      englishName: "Young Mania Rating Scale (YMRS)",
      description:
        "Young等编制，原版为临床他评量表，本实现使用自评简化版，仅作粗筛参考",
      duration: "约3-5分钟",
      questionsCount: 11,
      tags: ["躁狂", "双相", "快速"],
      category: "symptom",
    },
    {
      id: "mid60",
      title: "MID-60 多维解离量表",
      englishName: "Multidimensional Inventory of Dissociation (MID-60)",
      description:
        "多维解离量表，用0-10评估解离体验频率与严重程度，覆盖DID/OSDD、人格/现实解体、解离性失忆、PTSD与功能性神经症状，含12个子量表",
      duration: "约10-15分钟",
      questionsCount: 60,
      tags: ["解离", "创伤"],
      category: "symptom",
    },
    {
      id: "des2",
      title: "解离经验量表",
      englishName: "Dissociative Experiences Scale-II (DES-II)",
      description: "解离经验量表（DES-II），用0-100评估记忆缺失、人格/现实解体与吸收沉浸三类解离体验，国际常用的解离筛查工具",
      duration: "约10分钟",
      questionsCount: 28,
      tags: ["解离", "创伤", "快速"],
      category: "symptom",
    },
    {
      id: "sdq20",
      title: "躯体形式解离问卷",
      englishName: "Somatoform Dissociation Questionnaire-20 (SDQ-20)",
      description: "SDQ-20，用1-5评估过去一年躯体解离体验（麻木、瘫痪、知觉异常等），单维度总量表，含SDQ-5快速筛查子集",
      duration: "约5-8分钟",
      questionsCount: 20,
      tags: ["解离", "创伤", "躯体"],
      category: "symptom",
    },
    {
      id: "ybocs",
      title: "耶鲁-布朗强迫量表",
      englishName: "Yale-Brown Obsessive Compulsive Scale (Y-BOCS)",
      description: "Y-BOCS，用0-4评估强迫思维与强迫行为的严重程度（各5题），总分0-40，是不依赖具体症状内容的金标准评估工具",
      duration: "约5-8分钟",
      questionsCount: 10,
      tags: ["强迫", "焦虑", "快速"],
      category: "symptom",
    },
    {
      id: "ocir",
      title: "强迫量表修订版",
      englishName: "Obsessive-Compulsive Inventory - Revised (OCI-R)",
      description: "OCI-R，用0-4评估过去一个月强迫症状带来的困扰，含洗涤、检查、排序、强迫思维、中和、囤积6个子量表（总分0-72）",
      duration: "约5-8分钟",
      questionsCount: 18,
      tags: ["强迫", "焦虑", "快速"],
      category: "symptom",
    },
    {
      id: "ptsd",
      title: "创伤后应激严重度（PTSD）",
      englishName: "Severity of Posttraumatic Stress Symptoms (NSESSS)",
      description: "PTSD 严重度短量表（NSESSS，9 题）评估经历极端应激事件后过去 7 天的创伤后应激症状（闪回、回避、消极情绪、警觉增高）",
      duration: "约3-5分钟",
      questionsCount: 9,
      tags: ["创伤", "应激", "快速"],
      category: "symptom",
    },
    {
      id: "panic",
      title: "惊恐障碍严重度",
      englishName: "Severity Measure for Panic Disorder–Adult",
      description: "惊恐障碍成人严重度量表（DSM-5-TR，10 题），评估惊恐发作频率、担忧、躯体症状与回避",
      duration: "约2-4分钟",
      questionsCount: 10,
      tags: ["焦虑", "惊恐", "快速"],
      category: "symptom",
    },
    {
      id: "social",
      title: "社交焦虑障碍严重度",
      englishName: "Severity Measure for Social Anxiety Disorder–Adult",
      description: "社交焦虑（社交恐怖）成人严重度量表（DSM-5-TR，10 题），评估社交情境中的焦虑、躯体反应与回避",
      duration: "约2-4分钟",
      questionsCount: 10,
      tags: ["焦虑", "社交", "快速"],
      category: "symptom",
    },
    {
      id: "phobia",
      title: "特定恐怖症严重度",
      englishName: "Severity Measure for Specific Phobia–Adult",
      description: "特定恐怖症成人严重度量表（DSM-5-TR，10 题），评估对特定事物/情境的恐惧、躯体反应与回避",
      duration: "约2-4分钟",
      questionsCount: 10,
      tags: ["焦虑", "恐惧", "快速"],
      category: "symptom",
    },
    {
      id: "agora",
      title: "广场恐怖严重度",
      englishName: "Severity Measure for Agoraphobia–Adult",
      description: "广场恐怖成人严重度量表（DSM-5-TR，10 题），评估在人群、公共场所、交通工具、独自外出中的恐惧与回避",
      duration: "约2-4分钟",
      questionsCount: 10,
      tags: ["焦虑", "广场", "快速"],
      category: "symptom",
    },
    {
      id: "sepanx",
      title: "分离焦虑障碍严重度",
      englishName: "Severity Measure for Separation Anxiety Disorder–Adult",
      description: "分离焦虑障碍成人严重度量表（DSM-5-TR，10 题），评估与重要的人或家分离时的恐惧、担忧与回避",
      duration: "约2-4分钟",
      questionsCount: 10,
      tags: ["焦虑", "分离", "快速"],
      category: "symptom",
    },
    {
      id: "isi",
      title: "失眠严重程度指数",
      englishName: "Insomnia Severity Index (ISI)",
      description:
        "Morin等编制，评估过去2周失眠问题的性质、症状及日间影响",
      duration: "约2-3分钟",
      questionsCount: 7,
      tags: ["睡眠障碍", "快速"],
      category: "symptom",
    },
    {
      id: "multidim",
      title: "心理健康多维自评量表",
      englishName: "Multidimensional Mental Health Scale",
      description:
        "覆盖20个核心特征维度的综合自评工具，提供极简/快速/标准/深度四种模式，内置回答一致性与效度校验，支持乱序复测",
      duration: "约3-12分钟",
      questionsCount: 65,
      tags: [],
      category: "symptom",
    },
  ];

  return {
    success: true,
    data: testList,
  };
});
